### ISSUE TITLE
Audiomack link embed broken

### ISSUE THREAD

**Issue by ttcath** [audiomack/audiomack-api-examples#3]
Quick summary
The Audiomack link created before 2023.11.14 can embed into the post, like :

https://audiomack.com/ttcath/song/monday-32-ot-a-2023-mass-homily

but this one, cannot be embed into the post.

https://audiomack.com/ttcath/song/tuesday-32-ot-a-2023

I try to use another source, like:

https://open.firstory.me/embed/story/cloyi3qm2000001tociwxbym2

It work.

Steps to reproduce
1.create a post
2. choose embed block, paste any link from Audiomack website
3. the block return 404 error, the page not found

I also report to WordPress.com,see https://github.com/Automattic/wp-calypso/issues/84169

**Comment by karock** [comment]
thanks for the bug report, this should now work properly again.

**Comment by ttcath** [comment]
@karock actually, nope, the bugs still occurs. Please fix them at once.

**Comment by karock** [comment]
got a link to a page with audiomack embeds not working properly?

**Comment by ttcath** [comment]
nope. 

Please double check The entire posts under CATEGORIES 每日弥撒 with TAGS 每日礼仪 at [www.ttcath.org]
which shows at those page: https://ttcath.org/tag/%e6%af%8f%e6%97%a5%e7%a4%bc%e4%bb%aa/ 
and https://ttcath.org/sundayhomily/

some of them still report error 404 page not found at embed block. So please check them all.

Blessing

Justin

**Comment by karock** [comment]
All of the audiomack embeds I can find by clicking around on those pages are working properly for me. Couldn't find any requests that 404'd. If there's a specific post that contains an audiomack embed not working please link directly to the single post. Also try clearing your browser cache perhaps.
